backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Info"
        name: contact_info
        file: site/settings/siteInfo.json
        fields:
          - { label: "Header Address", name: "headerAddress", widget: "string" }
          - label: "Full Business Address"
            name: "fullBusinessAddress"
            widget: "object"
            required: false
            fields:
              - {
                  label: "Street",
                  name: "street",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "City",
                  name: "city",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Postal Code",
                  name: "postalCode",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "State",
                  name: "state",
                  widget: "string",
                  required: false,
                }

          - { label: "Support Email", name: "supportEmail", widget: "string" }
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Facebook Link", name: "facebookLink", widget: "string" }
          - {
              label: "YouTube Link",
              name: "youtubeLink",
              required: false,
              widget: "string",
            }
  - name: "galleryPosts"
    label: "Gallery Post"
    folder: "content/galleryPosts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    media_folder: "static/img"
    public_folder: "static/img"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    media_folder: "/"
    public_folder: "/"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Short Description",
          name: "shortDescription",
          widget: "string",
        }
      - { label: "Home Facing Image", name: "homeImage", widget: "image" }
      - { label: "Details Facing Image", name: "detailsImage", widget: "image" }
      - {
          label: "Details Facing Description",
          name: "detailsDescription",
          widget: "text",
        }
      - {
          label: "Details Facing Features Description",
          name: "detailsFeaturesDescription",
          widget: "text",
        }
      - { label: "Before Image", name: "beforeImage", widget: "image" }
      - { label: "After Image", name: "afterImage", widget: "image" }
      - {
          label: "Results Description",
          name: "resultsDescription",
          widget: "text",
        }
