backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
logo_url: https://d33wubrfki0l68.cloudfront.net/6749674d71524fae87977fff52b0a8707e08a800/31877/static/lightlogo-0eea8f26954d519c8fb75d40e97efffe.png
display_url: https://roosepaint.com

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    media_folder: "images"
    public_folder: "images"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - {
          label: "Header Image",
          name: "headerImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Main Image",
          name: "image",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Sidebar Image",
          name: "sidebarImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Side Banner Image",
          name: "sidebannerImage",
          choose_url: false,
          required: false,
          widget: "image",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Published By", name: "publisherName", widget: "string" }
      - { label: "General Page Summary", name: "description", widget: "text" }
      - {
          label: "Body",
          name: "body",
          modes: ["rich_text"],
          widget: "markdown",
        }
  - name: "settings"
    label: "General Site Info"
    files:
      - label: "Info"
        name: contact_info
        file: site/settings/siteInfo.json
        fields:
          - { label: "Header Address", name: "headerAddress", widget: "string" }
          - {
              label: "Google Maps Address",
              name: "googleMapsAddressLink",
              widget: "string",
            }
          - {
              label: "Google Maps Embed Link",
              name: "googleMapsEmbedLink",
              widget: "string",
            }
          - label: "Full Business Address"
            name: "fullBusinessAddress"
            widget: "object"
            required: false
            fields:
              - {
                  label: "Street",
                  name: "street",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "City",
                  name: "city",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Postal Code",
                  name: "postalCode",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "State",
                  name: "state",
                  widget: "string",
                  required: false,
                }

          - { label: "Support Email", name: "supportEmail", widget: "string" }
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Facebook Link", name: "facebookLink", widget: "string" }
          - { label: "Jobber Link", name: "jobberLink", widget: "string" }
          - {
              label: "YouTube Link",
              name: "youtubeLink",
              required: false,
              widget: "string",
            }
  - name: "galleryPosts"
    label: "Gallery Post"
    folder: "content/galleryPosts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    media_folder: "images"
    public_folder: "images"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", choose_url: false, widget: "image" }
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{title}}"
    media_folder: "images"
    public_folder: "images"
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Short Description",
          name: "shortDescription",
          widget: "string",
        }
      - {
          label: "Home Facing Image",
          name: "homeImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Details Facing Image",
          name: "detailsImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Details Facing Description",
          name: "detailsDescription",
          widget: "text",
        }
      - {
          label: "Details Facing Features Description",
          name: "detailsFeaturesDescription",
          widget: "text",
        }
      - {
          label: "Before Image",
          name: "beforeImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "After Image",
          name: "afterImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Results Description",
          name: "resultsDescription",
          widget: "text",
        }
      - {
          label: "YouTube Video Emmbed Link",
          name: "youtubeVideoEmbedLink",
          widget: "string",
          required: false,
        }

      - {
          label: "Call to Action Image",
          name: "actionImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Call to Action Tagline",
          name: "actionTagline",
          widget: "string",
        }
      - { label: "Call to Action Title", name: "actionTitle", widget: "string" }
      - {
          label: "Call to Action Button Text",
          name: "actionButtonText",
          widget: "string",
          default: "Get Started",
        }
      - {
          label: "Call to Action Button Link",
          name: "actionButtonLink",
          widget: "string",
          default: "https://clienthub.getjobber.com/client_hubs/66a10fe9-55e4-46ed-b1f4-f244789fa028/public/work_request/new?source=social_media",
        }
  - name: "homeContent"
    label: "Home Page Content"
    folder: "content/homeContent"
    create: false
    media_folder: "images"
    public_folder: "images"
    slug: "{{year}}-{{month}}-{{day}}_index"
    editor:
      preview: true
    fields:
      - { label: "Tagline", name: "mainTagline", widget: "string" }
      - { label: "Title", name: "mainTitle", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Button Text", name: "buttonText", widget: "string" }
      - {
          label: "Title Background Image",
          name: "mainImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Large About Image",
          name: "largeAboutImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Circle About Image",
          name: "circleAboutImage",
          choose_url: false,
          widget: "image",
        }
      - { label: "About Tagline", name: "aboutTagline", widget: "string" }
      - { label: "About Title", name: "aboutTitle", widget: "string" }
      - { label: "About Subtitle", name: "aboutSubtitle", widget: "string" }
      - { label: "About Description", name: "aboutDescription", widget: "text" }
      - {
          label: "Company Owner Image",
          name: "companyOwnerImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Company Owner Signature",
          name: "companyOwnerSignature",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Company Owner Name",
          name: "companyOwnerName",
          widget: "string",
        }
      - {
          label: "Company Owner Title",
          name: "companyOwnerTitle",
          widget: "string",
        }
      - { label: "Services Tagline", name: "servicesTagline", widget: "string" }
      - { label: "Services Title", name: "servicesTitle", widget: "string" }
  - name: "aboutContent"
    label: "About Page Content"
    folder: "content/aboutContent"
    create: false
    media_folder: "images"
    public_folder: "images"
    slug: "{{year}}-{{month}}-{{day}}_index"
    editor:
      preview: true
    fields:
      - { label: "Tagline", name: "mainTagline", widget: "string" }
      - { label: "Title", name: "mainTitle", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }

      - { label: "Card 1 Title", name: "card1Title", widget: "string" }
      - {
          label: "Card 1 Description",
          name: "card1Description",
          widget: "string",
        }
      - { label: "Card 1 Link", name: "card1Link", widget: "string" }

      - { label: "Card 2 Title", name: "card2Title", widget: "string" }
      - {
          label: "Card 2 Description",
          name: "card2Description",
          widget: "string",
        }
      - { label: "Card 2 Link", name: "card2Link", widget: "string" }

      - {
          label: "Upper Left Image",
          name: "upperLeftImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Upper Right Image",
          name: "upperRightImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Lower Left Image",
          name: "lowerLeftImage",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Lower Right Image",
          name: "lowerRightImage",
          choose_url: false,
          widget: "image",
        }

      - {
          label: "Section 2 Image",
          name: "section2Image",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Section 2 Tagline",
          name: "section2Tagline",
          widget: "string",
        }
      - { label: "Section 2 Title", name: "section2Title", widget: "string" }
      - {
          label: "Section 2 Description",
          name: "section2Description",
          widget: "text",
        }

      - {
          label: "Section 2 Descriptor 1 Image",
          name: "section2Descriptor1Image",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Section 2 Descriptor 1 Title",
          name: "section2Descriptor1Title",
          widget: "text",
        }
      - {
          label: "Section 2 Descriptor 1 Description",
          name: "section2Descriptor1Description",
          widget: "text",
        }

      - {
          label: "Section 2 Descriptor 2 Image",
          name: "section2Descriptor2Image",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Section 2 Descriptor 2 Title",
          name: "section2Descriptor2Title",
          widget: "text",
        }
      - {
          label: "Section 2 Descriptor 2 Description",
          name: "section2Descriptor2Description",
          widget: "text",
        }

      - {
          label: "Section 2 Descriptor 3 Image",
          name: "section2Descriptor3Image",
          choose_url: false,
          widget: "image",
        }
      - {
          label: "Section 2 Descriptor 3 Title",
          name: "section2Descriptor3Title",
          widget: "text",
        }
      - {
          label: "Section 2 Descriptor 3 Description",
          name: "section2Descriptor3Description",
          widget: "text",
        }
